version: 2
updates:
- package-ecosystem: docker
  directory: "/api"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 15
- package-ecosystem: docker
  directory: "/web-ui"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 15
- package-ecosystem: nuget
  directory: "/api"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 15
- package-ecosystem: npm
  directory: "/web-ui"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 15  
